--------------------------------------------------------
--  DDL for Procedure CARGARAUDIT_TEST_CAMPOVAC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."CARGARAUDIT_TEST_CAMPOVAC" AS 
BEGIN
 execute immediate 'TRUNCATE TABLE ALM_REPORT.AUDIT_TEST_CAMPOVAC';
 
for x in (select DB_NAME, PROJECT_NAME, DOMAIN_NAME from alm_siteadmin_db_12.projects where DB_NAME = 'bch_qa_certificación_bch_qa_d') loop
execute immediate  'insert into ALM_REPORT.AUDIT_TEST_CAMPOVAC

SELECT
DISTINCT
TS.TS_TEST_ID "ID Test",
TS.TS_NAME "Nombre Test",
TS.TS_RESPONSIBLE "diseñador",
RQ.RQ_USER_12 "Coordinador" ,
REL.REL_USER_TEMPLATE_01 "Jpqa",

CASE  WHEN (TS.TS_USER_03 IS NULL OR
TS.TS_USER_01 IS NULL OR
TS.TS_USER_05 IS NULL OR
TS.TS_TYPE    IS NULL OR
TS.TS_USER_02 IS NULL OR
TS.TS_USER_07 IS NULL OR
TS.TS_USER_06 IS NULL) THEN ''Completar campos vacios''
ELSE ''OK'' END AS "Accion a Tomar",
''SERVIDOR TSOFT'' as SERVIDOR


FROM
'||x.db_name||'.TEST TS
LEFT JOIN '||x.db_name||'.REQ_COVER RC ON RC.RC_ENTITY_ID = TS_TEST_ID AND RC.RC_ENTITY_TYPE = ''TEST''
LEFT JOIN '||x.db_name||'.REQ RQ ON RQ.RQ_REQ_ID = RC.RC_REQ_ID
LEFT JOIN '||x.db_name||'.REQ_RELEASES RQRL ON RQRL.RQRL_REQ_ID = RQ.RQ_REQ_ID
LEFT JOIN '||x.db_name||'.RELEASES REL ON REL.REL_ID = RQRL.RQRL_RELEASE_ID
LEFT JOIN '||x.db_name||'.RELEASE_FOLDERS RF ON REL.REL_PARENT_ID = RF.RF_ID

WHERE
(
TS.TS_USER_03 IS NULL OR
TS.TS_USER_01 IS NULL OR
TS.TS_USER_05 IS NULL OR
TS.TS_TYPE    IS NULL OR
TS.TS_USER_02 IS NULL OR
TS.TS_USER_07 IS NULL OR
TS.TS_USER_06 IS NULL
)

AND RF.RF_PATH like ''AAAAAA%'' --or RF.RF_PATH like ''AAAAAB%'')

GROUP BY
TS.TS_TEST_ID,
TS.TS_NAME,
TS.TS_RESPONSIBLE,
RQ.RQ_USER_12,
REL.REL_USER_TEMPLATE_01,
TS.TS_USER_03,
TS.TS_USER_01,
TS.TS_USER_05,
TS.TS_TYPE,
TS.TS_USER_02,
TS.TS_USER_07,
TS.TS_USER_06

'; end loop;

execute immediate  'insert into ALM_REPORT.AUDIT_TEST_CAMPOVAC 
select * from AUDIT_TEST_CAMPOVAC@SERVER_BCH
';

END;

/
