--------------------------------------------------------
--  DDL for Procedure CARGAR_DATA_EXTRACT_MENSUAL_TB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."CARGAR_DATA_EXTRACT_MENSUAL_TB" AS 
BEGIN


execute immediate 'delete from DATA_EXTRACT_MENSUAL_TB
where SERVIDOR = ''SERVIDOR BCH''

';

execute immediate 'delete from DATA_EXTRACT_MENSUAL_TB
where FECHA_REGISTRO = TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')

';
execute immediate  'insert into ALM_REPORT.DATA_EXTRACT_MENSUAL_TB
SELECT
DISTINCT
''SERVIDOR TSOFT'' AS SERVIDOR,
''BCH_QA'' AS ESQUEMA,
R.REL_ID AS ID_REL,
R.REL_NAME AS NOMBRE_RELEASES,
R.REL_START_DATE AS FECHA_REPLAN_INI,
R.REL_USER_TEMPLATE_01  AS  JPQA,
R.REL_END_DATE AS FECHA_REPLAN_FIN,
TO_DATE(R.REL_USER_03, ''yyyy/mm/dd'' ) AS FECHA_INICIO,
TO_DATE(R.REL_USER_02, ''yyyy/mm/dd'' ) AS FECHA_FIN,

RC.RCYC_ID AS ID_CICLO,
RC.RCYC_NAME AS NOMBRE_CICLO,
RC.RCYC_USER_01 AS TIPO_CICLO,

MIN(TC.TC_EXEC_DATE) AS INICIO_ETAPA_DINAMICA,
MAX(TC.TC_EXEC_DATE) AS FIN_ETAPA_DINAMICA,
 
(SELECT COUNT(DISTINCT TC_ACTUAL_TESTER) 
FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.TESTCYCL
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES ON RCYC_ID = TC_ASSIGN_RCYC
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES ON REL_ID = RCYC_PARENT_ID 
WHERE REL_ID = R.REL_ID   ) AS CANTIDAD_TESTER,
 
COUNT(DISTINCT TC.TC_TESTCYCL_ID) AS CASOS_DEFINIDOS,
 
COUNT(DISTINCT CASE WHEN (TC.TC_STATUS = ''Passed'' OR TC.TC_STATUS = ''Failed''  OR TC.TC_STATUS = ''Not Completed'' OR
TC.TC_STATUS = ''Blocked'' ) THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_EJECUTADOS,
 
COUNT(DISTINCT CASE WHEN TC.TC_STATUS = ''Passed''  THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_EXITOSOS,
COUNT(DISTINCT CASE WHEN TC.TC_STATUS = ''Failed''  THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_FALLADOS,
 
 
COUNT(DISTINCT CASE WHEN (TC.TC_STATUS = ''Passed'' OR TC.TC_STATUS = ''Failed'' OR TC.TC_STATUS = ''Not Completed'' OR
TC.TC_STATUS = ''Blocked'') AND
TC.TC_EXEC_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')   AND
TC.TC_EXEC_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
--TC.TC_EXEC_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')   AND
--TC.TC_EXEC_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_EJE_MES,
 
-------------------------------EJECUCIONES----------------------------------------
COUNT (DISTINCT CASE WHEN (RN.RN_STATUS = ''Passed'' or RN.RN_STATUS = ''Failed'')  THEN RN.RN_RUN_ID END )  "Ejecuciones Ejecutadas" ,
COUNT (DISTINCT CASE WHEN RN.RN_STATUS = ''Passed''  THEN RN.RN_RUN_ID END )  "Ejecuciones Exitosas" ,
COUNT (DISTINCT CASE WHEN RN.RN_STATUS = ''Failed''  THEN RN.RN_RUN_ID END )  "Ejecuciones Falladas" ,
COUNT (DISTINCT CASE WHEN (RN.RN_STATUS = ''Passed'' or RN.RN_STATUS = ''Failed'' ) AND
RN.RN_EXECUTION_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') AND
RN.RN_EXECUTION_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
--RN.RN_EXECUTION_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') 
--AND RN.RN_EXECUTION_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
AND RN.RN_RUN_NAME NOT LIKE (''%Fast%'')
THEN RN.RN_RUN_ID END ) AS EJEC_EJE_MES,
 
COUNT (DISTINCT CASE WHEN (RN.RN_STATUS = ''Passed'' or RN.RN_STATUS = ''Failed'' ) AND
RN.RN_EXECUTION_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')  AND
RN.RN_EXECUTION_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'') AND
--RN.RN_EXECUTION_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')  AND
--RN.RN_EXECUTION_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'') AND
UPPER(RN.RN_SUBTYPE_ID)  IN (''hp.qc.run.QUICKTEST_TEST'', ''hp.qc.run.SERVICE-TEST'')   THEN RN.RN_RUN_ID END )  AS EJEC_AUTO_MES,
--LIKE ''%QUICKTEST_TEST%''

 
RQ.RQ_REQ_NAME AS REQUERIMIENTO,
 
RQ.RQ_USER_04 AS ESTADO_REQ,
 
--''||x.PROJECT_NAME||'' AS esquema,
 
RQ.RQ_USER_03 AS JDP_QA,
 
--''||x.DOMAIN_NAME||'' AS DOMINIO,
 
COUNT(DISTINCT CASE WHEN TC.TC_STATUS = ''Blocked''  THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_BLOQUEADOS,
 
ALM_REPORT.DIAS_LABORABLES(TO_DATE(R.REL_USER_03, ''yyyy/mm/dd'' ), sysdate) AS DIAS_TRANS,
 
(SELECT COUNT(distinct BG_BUG_ID) FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.BUG WHERE RC.RCYC_ID = BG_TARGET_RCYC) AS CANTIDAD_DEF_CICLO,
 
NVL((
SELECT
SUM(
CASE WHEN ((SELECT COUNT(AP.AP_NEW_VALUE )
FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.AUDIT_LOG AU
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.AUDIT_PROPERTIES AP ON AP.AP_ACTION_ID = AU.AU_ACTION_ID AND AP.AP_NEW_VALUE = ''Listo para Ejecutar''
--AND AP.AP_PROPERTY_NAME = ''06- Estado''  --Retrasa los tiempos
AND AP.AP_FIELD_NAME = ''BG_STATUS''	
WHERE AU.AU_ENTITY_ID = cast(B.BG_BUG_ID as varchar(200)))- 1  ) = -1 THEN 0 ELSE
((SELECT COUNT(AP.AP_NEW_VALUE )
FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.AUDIT_LOG AU
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.AUDIT_PROPERTIES AP ON AP.AP_ACTION_ID = AU.AU_ACTION_ID AND AP.AP_NEW_VALUE = ''Listo para Ejecutar''
AND AP.AP_FIELD_NAME = ''BG_STATUS''	
--AND AP.AP_PROPERTY_NAME = ''06- Estado''  --Retrasa los tiempos
WHERE AU.AU_ENTITY_ID = cast(B.BG_BUG_ID as varchar(200)))- 1  ) END )
FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.BUG    B
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES  ON REL_ID = B.BG_TARGET_REL
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES  ON RCYC_ID = BG_TARGET_RCYC
WHERE RCYC_ID = RC.RCYC_ID
) ,0) AS SUM_ITERACIONES,
 
NVL((
SELECT
AVG(
CASE WHEN B.BG_CLOSING_DATE IS NULL THEN  ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , SYSDATE ) ELSE 
ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , B.BG_CLOSING_DATE ) END - 1
) 
FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.BUG    B
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES  ON REL_ID = B.BG_TARGET_REL
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES  ON RCYC_ID = BG_TARGET_RCYC
WHERE RCYC_ID = RC.RCYC_ID),0) AS AÑEJAMIENTO,
 
NVL((SELECT
AVG(
CASE WHEN B.BG_CLOSING_DATE IS NULL THEN  ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , SYSDATE ) ELSE 
ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , B.BG_CLOSING_DATE ) END -1)
FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.BUG    B
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES  ON REL_ID = B.BG_TARGET_REL
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES  ON RCYC_ID = BG_TARGET_RCYC
WHERE
B.BG_SEVERITY IN (''3-High'',''4-Very High'',''5-Urgent'')
AND RCYC_ID = RC.RCYC_ID),0) AS AÑEJAMIENTO_INVA,
 
 
to_date(RC.RCYC_USER_02,''yyyy/mm/dd'' ) AS FECHA_INI_CICLO,
to_date(RC.RCYC_USER_03,''yyyy/mm/dd'' ) AS FECHA_FIN_CICLO,
 
ALM_REPORT.DIAS_LABORABLES(
to_date(RC.RCYC_USER_02,''yyyy/mm/dd'' ) , to_date(RC.RCYC_USER_03,''yyyy/mm/dd'' )
) AS DIAS_TRANS_CICLO,
 
NVL(
ALM_REPORT.DIAS_LABORABLES(
MIN(TC.TC_EXEC_DATE) ,
MAX(TC.TC_EXEC_DATE)
),0) AS DIAS_TRANS_DINAMICOS,
 
NVL((SELECT DISTINCT  MAX(RQ_USER_33)
FROM  BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ,  BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES 
WHERE RQ_TYPE_ID IN (107,117,119) AND RQRL_RELEASE_ID = R.REL_ID and RQRL_REQ_ID = RQ_REQ_ID), 
''No tiene trazabilidad al requerimiento o se encuentra vacio'') AS COORDINADOR,
 
--to_date(RC.RCYC_USER_02,''yyyy-mm-dd'') AS FECHA_INI_CICLO,
 
RC.RCYC_START_DATE AS FECHA_REPLAN_INI_CICLO,
R.REL_USER_01 AS N_ART,

CASE
WHEN RF3.RF_NAME = ''Continuidad'' THEN ''MALO''
WHEN RF2.RF_NAME = ''Continuidad'' THEN ''MALO''
WHEN RF.RF_NAME = ''Continuidad'' THEN ''MALO''
ELSE ''OK'' END AS VALIDACION,
TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') as FECHA_REGISTRO,
--TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') AS FECHA_REGISTRO, 
-----------------------------------------------------------------------------------

NVL((SELECT ''ACTIVO EN EL MES''
FROM
BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES 
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES  ON RCYC_PARENT_ID = REL_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.TESTCYCL  ON TC_ASSIGN_RCYC = RCYC_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RUN  ON RN_TESTCYCL_ID = TC_TESTCYCL_ID
WHERE 1=1
AND RN_EXECUTION_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/YYYY'') 
AND RN_EXECUTION_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
--AND RN_EXECUTION_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') 
--AND RN_EXECUTION_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
AND REL_ID = R.REL_ID 
GROUP BY REL_ID, REL_NAME), ''NO ACTIVO'') AS PROYECTO_ACTIVO



FROM
BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES R
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES RC ON RC.RCYC_PARENT_ID = R.REL_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.BUG B ON B.BG_DETECTED_IN_RCYC = RC.RCYC_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.TESTCYCL TC ON TC.TC_ASSIGN_RCYC = RC.RCYC_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RUN RN ON RN.RN_TESTCYCL_ID = TC.TC_TESTCYCL_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES RQRL ON RQRL.RQRL_REQ_ID = R.REL_ID 
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ RQ ON RQ.RQ_REQ_ID = RQRL.RQRL_REQ_ID 
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF.RF_PARENT_ID
LEFT JOIN  BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID


where RC.RCYC_NAME not LIKE (''%IDC%'') 
AND(RF.RF_PATH not like ''AAAAAD%''  AND RF.RF_PATH not like ''AAAAADAAC%'' AND RF.RF_PATH not like ''AAAAADAAB%'' AND RF.RF_PATH not like ''AAAAAG%'')


--AND R.REL_ID IN (''1870'', ''1957'', ''1956'')
 
GROUP BY  RC.RCYC_ID,
R.REL_ID,  
R.REL_NAME, 
R.REL_START_DATE ,
R.REL_END_DATE ,
R.REL_USER_TEMPLATE_01,
TO_DATE(R.REL_USER_03, ''yyyy/mm/dd'' ) ,
TO_DATE(R.REL_USER_02, ''yyyy/mm/dd'' ) ,
RC.RCYC_NAME, 
RC.RCYC_USER_01,
to_date(RC.RCYC_USER_02,''yyyy/mm/dd'' ) ,
to_date(RC.RCYC_USER_03,''yyyy/mm/dd'' ),
RC.RCYC_USER_02,
RQ.RQ_REQ_NAME, RQ.RQ_USER_04, 
RQ.RQ_USER_03,
RC.RCYC_START_DATE, 
R.REL_USER_01, 
RF3.RF_NAME, 
RF2.RF_NAME, 
RF.RF_NAME, 
B.BG_BUG_ID

';

execute immediate  'insert into ALM_REPORT.DATA_EXTRACT_MENSUAL_TB

SELECT
DISTINCT
''SERVIDOR TSOFT'' AS SERVIDOR,
''QA_QA'' AS ESQUEMA,
R.REL_ID AS ID_REL,
R.REL_NAME AS NOMBRE_RELEASES,
R.REL_START_DATE AS FECHA_REPLAN_INI,
R.REL_USER_05  AS  JPQA,
R.REL_END_DATE AS FECHA_REPLAN_FIN,
TO_DATE(R.REL_USER_01, ''yyyy/mm/dd'' ) AS FECHA_INICIO,
TO_DATE(R.REL_USER_03, ''yyyy/mm/dd'' ) AS FECHA_FIN,

RC.RCYC_ID AS ID_CICLO,
RC.RCYC_NAME AS NOMBRE_CICLO,
RC.RCYC_USER_03 AS TIPO_CICLO,

MIN(TC.TC_EXEC_DATE) AS INICIO_ETAPA_DINAMICA,
MAX(TC.TC_EXEC_DATE) AS FIN_ETAPA_DINAMICA,
 
(SELECT COUNT(DISTINCT TC_ACTUAL_TESTER) 
FROM QA_QA_DB0.TESTCYCL
JOIN QA_QA_DB0.RELEASE_CYCLES ON RCYC_ID = TC_ASSIGN_RCYC
JOIN QA_QA_DB0.RELEASES ON REL_ID = RCYC_PARENT_ID 
WHERE REL_ID = R.REL_ID   ) AS CANTIDAD_TESTER,
 
COUNT(DISTINCT TC.TC_TESTCYCL_ID) AS CASOS_DEFINIDOS,
 
COUNT(DISTINCT CASE WHEN (TC.TC_STATUS = ''Passed'' OR TC.TC_STATUS = ''Failed''  OR TC.TC_STATUS = ''Not Completed'' OR
TC.TC_STATUS = ''Blocked'' ) THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_EJECUTADOS,
 
COUNT(DISTINCT CASE WHEN TC.TC_STATUS = ''Passed''  THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_EXITOSOS,
COUNT(DISTINCT CASE WHEN TC.TC_STATUS = ''Failed''  THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_FALLADOS,
 
 
COUNT(DISTINCT CASE WHEN (TC.TC_STATUS = ''Passed'' OR TC.TC_STATUS = ''Failed'' OR TC.TC_STATUS = ''Not Completed'' OR
TC.TC_STATUS = ''Blocked'') AND
TC.TC_EXEC_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/YYYY'')   AND
TC.TC_EXEC_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
--TC.TC_EXEC_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')   AND
--TC.TC_EXEC_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_EJE_MES,
 
-------------------------------EJECUCIONES----------------------------------------
COUNT (DISTINCT CASE WHEN (RN.RN_STATUS = ''Passed'' or RN.RN_STATUS = ''Failed'')  THEN RN.RN_RUN_ID END )  "Ejecuciones Ejecutadas" ,
COUNT (DISTINCT CASE WHEN RN.RN_STATUS = ''Passed''  THEN RN.RN_RUN_ID END )  "Ejecuciones Exitosas" ,
COUNT (DISTINCT CASE WHEN RN.RN_STATUS = ''Failed''  THEN RN.RN_RUN_ID END )  "Ejecuciones Falladas" ,
COUNT (DISTINCT CASE WHEN (RN.RN_STATUS = ''Passed'' or RN.RN_STATUS = ''Failed'' ) AND
RN.RN_EXECUTION_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/YYYY'') AND
RN.RN_EXECUTION_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
--RN.RN_EXECUTION_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') AND
--RN.RN_EXECUTION_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
AND RN.RN_RUN_NAME NOT LIKE (''%Fast%'')
THEN RN.RN_RUN_ID END ) AS EJEC_EJE_MES,
 
COUNT (DISTINCT CASE WHEN (RN.RN_STATUS = ''Passed'' or RN.RN_STATUS = ''Failed'' ) AND
RN.RN_EXECUTION_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/YYYY'')  AND
RN.RN_EXECUTION_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'') AND
--RN.RN_EXECUTION_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'')  AND
--RN.RN_EXECUTION_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'') AND
UPPER(RN.RN_SUBTYPE_ID)  IN (''hp.qc.run.QUICKTEST_TEST'', ''hp.qc.run.SERVICE-TEST'')   THEN RN.RN_RUN_ID END )  AS EJEC_AUTO_MES,
 
RQ.RQ_REQ_NAME AS REQUERIMIENTO,
 
RQ.RQ_USER_02 AS ESTADO_REQ,
 
--''||x.PROJECT_NAME||'' AS esquema,
 
RQ.RQ_USER_03 AS JDP_QA,
 
--''||x.DOMAIN_NAME||'' AS DOMINIO,
 
COUNT(DISTINCT CASE WHEN TC.TC_STATUS = ''Blocked''  THEN TC.TC_TESTCYCL_ID END  ) AS CASOS_BLOQUEADOS,
 
ALM_REPORT.DIAS_LABORABLES(TO_DATE(R.REL_USER_01, ''yyyy/mm/dd'' ), sysdate) AS DIAS_TRANS,
 
(SELECT COUNT(distinct BG_BUG_ID) FROM QA_QA_DB0.BUG WHERE RC.RCYC_ID = BG_TARGET_RCYC) AS CANTIDAD_DEF_CICLO,
 
NVL((
SELECT
SUM(
CASE WHEN ((SELECT COUNT(AP.AP_NEW_VALUE )
FROM QA_QA_DB0.AUDIT_LOG AU
JOIN QA_QA_DB0.AUDIT_PROPERTIES AP ON AP.AP_ACTION_ID = AU.AU_ACTION_ID AND AP.AP_NEW_VALUE = ''Listo para Ejecutar''
--AND AP.AP_PROPERTY_NAME = ''06- Estado''  --Retrasa los tiempos
AND AP.AP_FIELD_NAME = ''BG_STATUS''	
WHERE AU.AU_ENTITY_ID = cast(B.BG_BUG_ID as varchar(200)))- 1  ) = -1 THEN 0 ELSE
((SELECT COUNT(AP.AP_NEW_VALUE )
FROM QA_QA_DB0.AUDIT_LOG AU
JOIN QA_QA_DB0.AUDIT_PROPERTIES AP ON AP.AP_ACTION_ID = AU.AU_ACTION_ID AND AP.AP_NEW_VALUE = ''Listo para Ejecutar''
--AND AP.AP_PROPERTY_NAME = ''06- Estado''  --Retrasa los tiempos
AND AP.AP_FIELD_NAME = ''BG_STATUS''
WHERE AU.AU_ENTITY_ID = cast(B.BG_BUG_ID as varchar(200)))- 1  ) END )
FROM QA_QA_DB0.BUG    B
JOIN QA_QA_DB0.RELEASES  ON REL_ID = B.BG_TARGET_REL
JOIN QA_QA_DB0.RELEASE_CYCLES  ON RCYC_ID = BG_TARGET_RCYC
WHERE RCYC_ID = RC.RCYC_ID
) ,0) AS SUM_ITERACIONES,
 
NVL((
SELECT
AVG(
CASE WHEN B.BG_CLOSING_DATE IS NULL THEN  ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , SYSDATE ) ELSE 
ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , B.BG_CLOSING_DATE ) END - 1
) 
FROM QA_QA_DB0.BUG    B
JOIN QA_QA_DB0.RELEASES  ON REL_ID = B.BG_TARGET_REL
JOIN QA_QA_DB0.RELEASE_CYCLES  ON RCYC_ID = BG_TARGET_RCYC
WHERE RCYC_ID = RC.RCYC_ID),0) AS AÑEJAMIENTO,
 
NVL((SELECT
AVG(
CASE WHEN B.BG_CLOSING_DATE IS NULL THEN  ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , SYSDATE ) ELSE 
ALM_REPORT.DIAS_LABORABLES(B.BG_DETECTION_DATE , B.BG_CLOSING_DATE ) END -1)
FROM QA_QA_DB0.BUG    B
JOIN QA_QA_DB0.RELEASES  ON REL_ID = B.BG_TARGET_REL
JOIN QA_QA_DB0.RELEASE_CYCLES  ON RCYC_ID = BG_TARGET_RCYC
WHERE
B.BG_SEVERITY IN (''3-High'',''4-Very High'',''5-Urgent'')
AND RCYC_ID = RC.RCYC_ID),0) AS AÑEJAMIENTO_INVA,
 
 
to_date(RC.RCYC_USER_01,''yyyy/mm/dd'' ) AS FECHA_INI_CICLO,
to_date(RC.RCYC_USER_02,''yyyy/mm/dd'' ) AS FECHA_FIN_CICLO,
 
ALM_REPORT.DIAS_LABORABLES(
to_date(RC.RCYC_USER_01,''yyyy/mm/dd'' ) , to_date(RC.RCYC_USER_02,''yyyy/mm/dd'' )
) AS DIAS_TRANS_CICLO,
 
NVL(
ALM_REPORT.DIAS_LABORABLES(
MIN(TC.TC_EXEC_DATE) ,
MAX(TC.TC_EXEC_DATE)
),0) AS DIAS_TRANS_DINAMICOS,
 
NVL((SELECT DISTINCT  MAX(RQ_REQ_AUTHOR)
FROM  QA_QA_DB0.REQ,  QA_QA_DB0.REQ_RELEASES 
WHERE RQ_TYPE_ID IN (3) AND RQRL_RELEASE_ID = R.REL_ID and RQRL_REQ_ID = RQ_REQ_ID), 
''No tiene trazabilidad al requerimiento o se encuentra vacio'') AS COORDINADOR,
 
--to_date(RC.RCYC_USER_02,''yyyy-mm-dd'') AS FECHA_INI_CICLO,
 
RC.RCYC_START_DATE AS FECHA_REPLAN_INI_CICLO,
R.REL_USER_04 AS N_ART,

CASE
WHEN RF3.RF_NAME = ''Continuidad'' THEN ''MALO''
WHEN RF2.RF_NAME = ''Continuidad'' THEN ''MALO''
WHEN RF.RF_NAME = ''Continuidad'' THEN ''MALO''
ELSE ''OK'' END AS VALIDACION,
TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') as FECHA_REGISTRO,
--TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') AS FECHA_REGISTRO,


NVL((SELECT ''ACTIVO EN EL MES''
FROM
QA_QA_DB0.RELEASES 
LEFT JOIN  QA_QA_DB0.RELEASE_CYCLES  ON RCYC_PARENT_ID = REL_ID
LEFT JOIN  QA_QA_DB0.TESTCYCL  ON TC_ASSIGN_RCYC = RCYC_ID
LEFT JOIN  QA_QA_DB0.RUN  ON RN_TESTCYCL_ID = TC_TESTCYCL_ID
WHERE 1=1
AND RN_EXECUTION_DATE >= TO_DATE(''01/''||TO_CHAR(SYSDATE,''mm'')||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/YYYY'') 
AND RN_EXECUTION_DATE <= TO_DATE(to_char(last_day(SYSDATE),''dd'')||''/''||TO_CHAR(SYSDATE,''mm'')||''/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
--AND RN_EXECUTION_DATE >= TO_DATE(''01/09/''||TO_CHAR(SYSDATE,''YYYY''),''dd/mm/yyyy'') 
--AND RN_EXECUTION_DATE <= TO_DATE(''30/09/''||TO_CHAR(SYSDATE,''YYYY''), ''dd/mm/yyyy'')
AND REL_ID = R.REL_ID 
GROUP BY REL_ID, REL_NAME), ''NO ACTIVO'') AS PROYECTO_ACTIVO
-----------------------------------------------------------------------------------
 
FROM
QA_QA_DB0.RELEASES R
LEFT JOIN  QA_QA_DB0.RELEASE_CYCLES RC ON RC.RCYC_PARENT_ID = R.REL_ID
LEFT JOIN  QA_QA_DB0.BUG B ON B.BG_DETECTED_IN_RCYC = RC.RCYC_ID
LEFT JOIN  QA_QA_DB0.TESTCYCL TC ON TC.TC_ASSIGN_RCYC = RC.RCYC_ID
LEFT JOIN  QA_QA_DB0.RUN RN ON RN.RN_TESTCYCL_ID = TC.TC_TESTCYCL_ID
LEFT JOIN  QA_QA_DB0.REQ_RELEASES RQRL ON RQRL.RQRL_REQ_ID = R.REL_ID 
LEFT JOIN  QA_QA_DB0.REQ RQ ON RQ.RQ_REQ_ID = RQRL.RQRL_REQ_ID 
LEFT JOIN  QA_QA_DB0.RELEASE_FOLDERS RF ON RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN  QA_QA_DB0.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF.RF_PARENT_ID
LEFT JOIN  QA_QA_DB0.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID


where RC.RCYC_NAME not LIKE (''%IDC%'')
--AND R.REL_ID = ''1432''
 
GROUP BY  RC.RCYC_ID,
R.REL_ID,  
R.REL_NAME, 
R.REL_START_DATE ,
R.REL_END_DATE ,
R.REL_USER_05,
TO_DATE(R.REL_USER_03, ''yyyy/mm/dd'' ) ,
TO_DATE(R.REL_USER_01, ''yyyy/mm/dd'' ) ,
RC.RCYC_NAME, 
RC.RCYC_USER_01,
to_date(RC.RCYC_USER_02,''yyyy/mm/dd'' ) ,
--to_date(RC.RCYC_USER_03,''yyyy/mm/dd'' ),
--RC.RCYC_USER_02,
RQ.RQ_REQ_NAME, 
--RQ.RQ_USER_04, 
RQ.RQ_USER_03,
RC.RCYC_START_DATE, 
--RQ_USER_09,
--R.REL_USER_01, 
RF3.RF_NAME, 
RF2.RF_NAME, 
RF.RF_NAME, 
B.BG_BUG_ID,
RC.RCYC_USER_03,
RQ_USER_02,
REL_USER_04

';

execute immediate  'insert into ALM_REPORT.DATA_EXTRACT_MENSUAL_TB 
select * from DATA_EXTRACT_MENSUAL_TB@SERVER_BCH
';

END;

/
