--------------------------------------------------------
--  DDL for Procedure cargarCALIDAD_DESARROLLO_AGIL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."cargarCALIDAD_DESARROLLO_AGIL" AS
BEGIN
execute immediate 'TRUNCATE TABLE ALM_REPORT.CALIDAD_DESARROLLO_AGIL';

for x in (select DB_NAME, PROJECT_NAME, DOMAIN_NAME  from alm_siteadmin_db_12.projects where DB_NAME = 'qa_qa_db0') loop
execute immediate  'insert into ALM_REPORT.CALIDAD_DESARROLLO_AGIL 

SELECT 
DISTINCT REL.REL_NAME AS PROYECTO,
RCY.RCYC_NAME AS NOMBRE_CICLO,
nvl (COUNT(DISTINCT TC.TC_TESTCYCL_ID),0) CASOS_DEFINIDOS,
NVL (cas_fal.CASOS_FALLADOS,0)CASOS_FALLADOS,
NVL  (DEFEC.DEFECTOS_CICLOS,0) DEFECTOS_CICLOS ,
NVL (COUNT(DISTINCT  RN.RN_RUN_ID )/COUNT(DISTINCT TC.TC_TESTCYCL_ID) ,0) AS PORCEN_,
DEFEC.ANEJAMINETO,
NVL (CR.CANT_REIN,0) AS DEFEC_REINCIDENTES,
''SERVIDOR TSOFT'' as SERVIDOR

FROM '||x.db_name||'.RELEASES REL
inner JOIN '||x.db_name||'.RELEASE_CYCLES RCY ON  RCY.RCYC_PARENT_ID=REL.REL_ID
inner JOIN '||x.db_name||'.TESTCYCL TC  ON RCY.RCYC_ID=TC.TC_ASSIGN_RCYC
inner JOIN '||x.db_name||'.RUN RN ON (RN.RN_TESTCYCL_ID = TC.TC_TESTCYCL_ID or RN.RN_ASSIGN_RCYC = RCY.RCYC_ID )

LEFT JOIN (SELECT RCYC_ID,count(BG_BUG_ID) as CANT_REIN FROM (

SELECT DISTINCT BG_BUG_ID, BG_TARGET_RCYC,COUNT (AP_NEW_VALUE) 
                        FROM  '||x.db_name||'.BUG B
                        JOIN  '||x.db_name||'.AUDIT_LOG  ON AU_ENTITY_ID = BG_BUG_ID
                        JOIN '||x.db_name||'.AUDIT_PROPERTIES  ON AP_ACTION_ID = AU_ACTION_ID
                        WHERE AU_ENTITY_TYPE = ''BUG'' AND AP_PROPERTY_NAME IN (''06 - Estado'') AND AP_NEW_VALUE  = ''Reopen''
                        GROUP BY BG_BUG_ID,BG_TARGET_RCYC)
                        INNER JOIN '||x.db_name||'.RELEASE_CYCLES RCY ON  RCY.RCYC_ID=BG_TARGET_RCYC
                        group by RCYC_ID) CR ON CR.RCYC_ID=RCY.RCYC_ID
LEFT JOIN (
            SELECT RCY.RCYC_ID,
            COUNT(distinct BG.BG_BUG_ID) DEFECTOS_CICLOS,
            NVL (max  (CASE 
      WHEN BG.BG_CLOSING_DATE IS NULL THEN  ALM_REPORT.DIASENTRE(BG.BG_DETECTION_DATE , SYSDATE ) 
      ELSE ALM_REPORT.DIASENTRE(BG.BG_DETECTION_DATE , BG.BG_CLOSING_DATE ) END) ,0) AS ANEJAMINETO
            FROM  '||x.db_name||'.RELEASE_CYCLES RCY
            inner  JOIN  '||x.db_name||'.BUG BG ON  BG.BG_TARGET_RCYC=RCY.RCYC_ID 
            GROUP BY
            RCY.RCYC_ID
) DEFEC ON DEFEC.RCYC_ID=RCY.RCYC_ID


left join (
SELECT 
RCY.RCYC_ID,
NVL (COUNT(DISTINCT  RN.RN_RUN_ID ),0)CASOS_FALLADOS
FROM '||x.db_name||'.RELEASES REL
inner JOIN '||x.db_name||'.RELEASE_CYCLES RCY ON  RCY.RCYC_PARENT_ID=REL.REL_ID
inner JOIN '||x.db_name||'.TESTCYCL TC  ON RCY.RCYC_ID=TC.TC_ASSIGN_RCYC
inner JOIN '||x.db_name||'.RUN RN ON (RN.RN_TESTCYCL_ID = TC.TC_TESTCYCL_ID or RN.RN_ASSIGN_RCYC = RCY.RCYC_ID )AND RN.RN_STATUS = ''Failed''
group by 
RCY.RCYC_ID
) cas_fal on cas_fal.RCYC_ID=RCY.RCYC_ID

GROUP BY
REL.REL_NAME,
RCY.RCYC_NAME,
cas_fal.CASOS_FALLADOS,
CR.CANT_REIN,
DEFEC.DEFECTOS_CICLOS,
DEFEC.ANEJAMINETO


'; end loop;


execute immediate  'insert into ALM_REPORT.CALIDAD_DESARROLLO_AGIL 
select * from CALIDAD_DESARROLLO_AGIL@SERVER_BCH
';

 
END;

/
