--------------------------------------------------------
--  DDL for Procedure cargarAutomatEjecucion
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."cargarAutomatEjecucion" AS
BEGIN
execute immediate 'TRUNCATE TABLE ALM_REPORT.CASOS_AUTOMATICOS_EJECUCION';

for x in (select DB_NAME, PROJECT_NAME, DESCRIPTION from alm_siteadmin_db_12.projects where domain_name in ('PROYECTOS') and PR_IS_ACTIVE = 'Y' ) loop
execute immediate  'insert into ALM_REPORT.CASOS_AUTOMATICOS_EJECUCION
SELECT
DISTINCT 
'''||x.PROJECT_NAME||'''  as PROYECTO,
R.REL_USER_04 AS JPQA,
COUNT(DISTINCT TC.TC_TESTCYCL_ID) AS "total cp planificado",
COUNT(DISTINCT CASE WHEN TC.TC_SUBTYPE_ID LIKE ''%MANUAL%'' THEN TC.TC_TESTCYCL_ID END  ) AS total_casos_manuales,
COUNT(DISTINCT CASE WHEN TC.TC_SUBTYPE_ID LIKE ''%QUICKTEST_TEST%'' THEN TC.TC_TESTCYCL_ID END ) as total_casos_automatizados,
COUNT(DISTINCT CASE WHEN TC.TC_EXEC_DATE IS NOT NULL AND TC.TC_SUBTYPE_ID LIKE ''%MANUAL%''  THEN TC.TC_TESTCYCL_ID END) as total_ejecutados_mtc,
COUNT(DISTINCT CASE WHEN TC.TC_EXEC_DATE IS NOT NULL AND TC.TC_SUBTYPE_ID LIKE ''%QUICKTEST_TEST%''  THEN TC.TC_TESTCYCL_ID END) as total_ejecutados_atm,

DECODE(
COUNT(DISTINCT TC.TC_TESTCYCL_ID), 0,0 ,
COUNT(DISTINCT CASE WHEN TC.TC_EXEC_DATE IS NOT NULL THEN TC.TC_TESTCYCL_ID END) / COUNT(DISTINCT TC.TC_TESTCYCL_ID)
) as porcentaje_avance,
''PROYECTOS'' as dominio

FROM
'||x.DB_NAME||'.RELEASES R 
LEFT JOIN '||x.DB_NAME||'.RELEASE_CYCLES RC ON RC.RCYC_PARENT_ID = R.REL_ID
LEFT JOIN '||x.DB_NAME||'.TESTCYCL TC ON TC.TC_ASSIGN_RCYC = RC.RCYC_ID 

WHERE
R.REL_NAME != ''Prueba''

GROUP BY
R.REL_USER_04 

';
end loop;

for x in (select DB_NAME, PROJECT_NAME, DESCRIPTION from alm_siteadmin_db_12.projects where domain_name in ('PROYECTOS') and PR_IS_ACTIVE = 'Y' ) loop
execute immediate  'insert into ALM_REPORT.CASOS_AUTOMATICOS_EJECUCION
SELECT
DISTINCT 
'''||x.PROJECT_NAME||'''  as PROYECTO,
R.REL_USER_04 AS JPQA,
COUNT(DISTINCT TC.TC_TESTCYCL_ID) AS "total cp planificado",
COUNT(DISTINCT CASE WHEN TC.TC_SUBTYPE_ID LIKE ''%MANUAL%'' THEN TC.TC_TESTCYCL_ID END  ) AS total_casos_manuales,
COUNT(DISTINCT CASE WHEN TC.TC_SUBTYPE_ID LIKE ''%QUICKTEST_TEST%'' THEN TC.TC_TESTCYCL_ID END ) as total_casos_automatizados,
COUNT(DISTINCT CASE WHEN TC.TC_EXEC_DATE IS NOT NULL AND TC.TC_SUBTYPE_ID LIKE ''%MANUAL%''  THEN TC.TC_TESTCYCL_ID END) as total_ejecutados_mtc,
COUNT(DISTINCT CASE WHEN TC.TC_EXEC_DATE IS NOT NULL AND TC.TC_SUBTYPE_ID LIKE ''%QUICKTEST_TEST%''  THEN TC.TC_TESTCYCL_ID END) as total_ejecutados_atm,

DECODE(
COUNT(DISTINCT TC.TC_TESTCYCL_ID), 0,0 ,
COUNT(DISTINCT CASE WHEN TC.TC_EXEC_DATE IS NOT NULL THEN TC.TC_TESTCYCL_ID END) / COUNT(DISTINCT TC.TC_TESTCYCL_ID)
) as porcentaje_avance,
''PROYECTOS'' as dominio

FROM
'||x.DB_NAME||'.RELEASES R1
LEFT JOIN CONTINUIDAD_AUTOMATIZACIÓN_DB.RELEASES R ON R.REL_USER_03 = R1.REL_USER_03
LEFT JOIN CONTINUIDAD_AUTOMATIZACIÓN_DB.RELEASE_CYCLES RC ON RC.RCYC_PARENT_ID = R.REL_ID
LEFT JOIN CONTINUIDAD_AUTOMATIZACIÓN_DB.TESTCYCL TC ON TC.TC_ASSIGN_RCYC = RC.RCYC_ID 


WHERE
R.REL_NAME != ''Prueba''

GROUP BY
R.REL_USER_04 

';
end loop;

end;

/
