--------------------------------------------------------
--  DDL for Procedure CARGAR_GLOBAL_AUDITORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."CARGAR_GLOBAL_AUDITORIA" AS 
BEGIN

execute immediate 'TRUNCATE TABLE ALM_REPORT.GLOBAL_AUDITORIA';


execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."jpqa") 
FROM ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET  WHERE ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."coordinador")
FROM ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET  WHERE ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."esquema" = "proyecto" ) as coordinador,

''RELEASES'' AS ENTIDAD,

''AU_REL_CICLOCARPETA_TESTSET'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."esquema") 
FROM ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET WHERE ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."estado") 
FROM ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET  WHERE ALM_REPORT.AU_REL_CICLOCARPETA_TESTSET."esquema" = "proyecto") as estado

from 
ALM_REPORT.PROYECTOS 

';



execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REL_NOMBRECICLOS."jpqa") 
FROM ALM_REPORT.AU_REL_NOMBRECICLOS  WHERE ALM_REPORT.AU_REL_NOMBRECICLOS."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REL_NOMBRECICLOS."coordinador")
FROM ALM_REPORT.AU_REL_NOMBRECICLOS  WHERE ALM_REPORT.AU_REL_NOMBRECICLOS."esquema" = "proyecto" ) as coordinador,

''RELEASES'' AS ENTIDAD,

''AU_REL_NOMBRECICLOS'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REL_NOMBRECICLOS."esquema") 
FROM ALM_REPORT.AU_REL_NOMBRECICLOS WHERE ALM_REPORT.AU_REL_NOMBRECICLOS."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO,

(SELECT SUM(ALM_REPORT.AU_REL_NOMBRECICLOS."estado")
FROM ALM_REPORT.AU_REL_NOMBRECICLOS  WHERE ALM_REPORT.AU_REL_NOMBRECICLOS."esquema" = "proyecto" ) as estado 

from 
ALM_REPORT.PROYECTOS 

';



execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REL_TRAZABILIDADREQ."jpqa") 
FROM ALM_REPORT.AU_REL_TRAZABILIDADREQ  WHERE ALM_REPORT.AU_REL_TRAZABILIDADREQ."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REL_TRAZABILIDADREQ."coordinador")
FROM ALM_REPORT.AU_REL_TRAZABILIDADREQ  WHERE ALM_REPORT.AU_REL_TRAZABILIDADREQ."esquema" = "proyecto" ) as coordinador,

''RELEASES'' AS ENTIDAD,

''AU_REL_TRAZABILIDADREQ'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REL_TRAZABILIDADREQ."esquema") 
FROM ALM_REPORT.AU_REL_TRAZABILIDADREQ WHERE ALM_REPORT.AU_REL_TRAZABILIDADREQ."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO,

(SELECT SUM(ALM_REPORT.AU_REL_TRAZABILIDADREQ."estado")
FROM ALM_REPORT.AU_REL_TRAZABILIDADREQ  WHERE ALM_REPORT.AU_REL_TRAZABILIDADREQ."esquema" = "proyecto" ) as estado 

from 
ALM_REPORT.PROYECTOS 

';

------------------------------------------------REQ-------------------------------------------------------------------------

execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REQ_NOMBRERELEASE."jpqa") 
FROM ALM_REPORT.AU_REQ_NOMBRERELEASE  WHERE ALM_REPORT.AU_REQ_NOMBRERELEASE."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REQ_NOMBRERELEASE."coordinador")
FROM ALM_REPORT.AU_REQ_NOMBRERELEASE  WHERE ALM_REPORT.AU_REQ_NOMBRERELEASE."esquema" = "proyecto" ) as coordinador,

''REQ'' AS ENTIDAD,

''AU_REQ_NOMBRERELEASE'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REQ_NOMBRERELEASE."esquema") 
FROM ALM_REPORT.AU_REQ_NOMBRERELEASE WHERE ALM_REPORT.AU_REQ_NOMBRERELEASE."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_REQ_NOMBRERELEASE."estado")
FROM ALM_REPORT.AU_REQ_NOMBRERELEASE  WHERE ALM_REPORT.AU_REQ_NOMBRERELEASE."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';


execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."jpqa") 
FROM ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS  WHERE ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."coordinador")
FROM ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS  WHERE ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."esquema" = "proyecto" ) as coordinador,

''REQ'' AS ENTIDAD,

''AU_REQ_NOMENCLATURAHIJOS'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."esquema") 
FROM ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS WHERE ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."estado")
FROM ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS  WHERE ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';


execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REQ_SINCOBERTURA."jpqa") 
FROM ALM_REPORT.AU_REQ_SINCOBERTURA  WHERE ALM_REPORT.AU_REQ_SINCOBERTURA."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REQ_SINCOBERTURA."coordinador")
FROM ALM_REPORT.AU_REQ_SINCOBERTURA  WHERE ALM_REPORT.AU_REQ_SINCOBERTURA."esquema" = "proyecto" ) as coordinador,

''REQ'' AS ENTIDAD,

''AU_REQ_SINCOBERTURA'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REQ_SINCOBERTURA."esquema") 
FROM ALM_REPORT.AU_REQ_SINCOBERTURA WHERE ALM_REPORT.AU_REQ_SINCOBERTURA."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."estado")
FROM ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS  WHERE ALM_REPORT.AU_REQ_NOMENCLATURAHIJOS."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';


execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_REQ_SINTRAZABILIDAD."jpqa") 
FROM ALM_REPORT.AU_REQ_SINTRAZABILIDAD  WHERE ALM_REPORT.AU_REQ_SINTRAZABILIDAD."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_REQ_SINTRAZABILIDAD."coordinador")
FROM ALM_REPORT.AU_REQ_SINTRAZABILIDAD  WHERE ALM_REPORT.AU_REQ_SINTRAZABILIDAD."esquema" = "proyecto" ) as coordinador,

''REQ'' AS ENTIDAD,

''AU_REQ_SINTRAZABILIDAD'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_REQ_SINTRAZABILIDAD."esquema") 
FROM ALM_REPORT.AU_REQ_SINTRAZABILIDAD WHERE ALM_REPORT.AU_REQ_SINTRAZABILIDAD."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_REQ_SINTRAZABILIDAD."estado")
FROM ALM_REPORT.AU_REQ_SINTRAZABILIDAD  WHERE ALM_REPORT.AU_REQ_SINTRAZABILIDAD."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';

-----------------------------------------TEST--------------------------------------------------

execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_TEST_CAMPOSVACIOS."jpqa") 
FROM ALM_REPORT.AU_TEST_CAMPOSVACIOS  WHERE ALM_REPORT.AU_TEST_CAMPOSVACIOS."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_TEST_CAMPOSVACIOS."coordinador")
FROM ALM_REPORT.AU_TEST_CAMPOSVACIOS WHERE ALM_REPORT.AU_TEST_CAMPOSVACIOS."esquema" = "proyecto" ) as coordinador,

''TEST'' AS ENTIDAD,

''AU_TEST_CAMPOSVACIOS'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_TEST_CAMPOSVACIOS."esquema") 
FROM ALM_REPORT.AU_TEST_CAMPOSVACIOS WHERE ALM_REPORT.AU_TEST_CAMPOSVACIOS."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_TEST_CAMPOSVACIOS."estado")
FROM ALM_REPORT.AU_TEST_CAMPOSVACIOS WHERE ALM_REPORT.AU_TEST_CAMPOSVACIOS."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';


execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_TEST_DESCRIPCION."jpqa") 
FROM ALM_REPORT.AU_TEST_DESCRIPCION  WHERE ALM_REPORT.AU_TEST_DESCRIPCION."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_TEST_DESCRIPCION."coordinador")
FROM ALM_REPORT.AU_TEST_DESCRIPCION WHERE ALM_REPORT.AU_TEST_DESCRIPCION."esquema" = "proyecto" ) as coordinador,

''TEST'' AS ENTIDAD,

''AU_TEST_DESCRIPCION'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_TEST_DESCRIPCION."esquema") 
FROM ALM_REPORT.AU_TEST_DESCRIPCION WHERE ALM_REPORT.AU_TEST_DESCRIPCION."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_TEST_DESCRIPCION."estado")
FROM ALM_REPORT.AU_TEST_DESCRIPCION WHERE ALM_REPORT.AU_TEST_DESCRIPCION."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';



execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_TEST_PASOS."jpqa") 
FROM ALM_REPORT.AU_TEST_PASOS  WHERE ALM_REPORT.AU_TEST_PASOS."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_TEST_PASOS."coordinador")
FROM ALM_REPORT.AU_TEST_PASOS WHERE ALM_REPORT.AU_TEST_PASOS."esquema" = "proyecto" ) as coordinador,

''TEST'' AS ENTIDAD,

''AU_TEST_PASOS'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_TEST_PASOS."esquema") 
FROM ALM_REPORT.AU_TEST_PASOS WHERE ALM_REPORT.AU_TEST_PASOS."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_TEST_PASOS."estado")
FROM ALM_REPORT.AU_TEST_PASOS WHERE ALM_REPORT.AU_TEST_PASOS."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';


execute immediate 'insert into ALM_REPORT.GLOBAL_AUDITORIA
select 
"proyecto",

(SELECT MAX(ALM_REPORT.AU_TEST_SINCOBERTURA."jpqa") 
FROM ALM_REPORT.AU_TEST_SINCOBERTURA  WHERE ALM_REPORT.AU_TEST_SINCOBERTURA."esquema" = "proyecto") as jpqa,

(SELECT MAX(ALM_REPORT.AU_TEST_SINCOBERTURA."coordinador")
FROM ALM_REPORT.AU_TEST_SINCOBERTURA WHERE ALM_REPORT.AU_TEST_SINCOBERTURA."esquema" = "proyecto" ) as coordinador,

''TEST'' AS ENTIDAD,

''AU_TEST_PASOS'' AS TABLA,


CASE WHEN (SELECT COUNT(ALM_REPORT.AU_TEST_SINCOBERTURA."esquema") 
FROM ALM_REPORT.AU_TEST_SINCOBERTURA WHERE ALM_REPORT.AU_TEST_SINCOBERTURA."esquema" = "proyecto" ) > 0 
THEN 0 ELSE 1 END as NUMERO ,

(SELECT SUM(ALM_REPORT.AU_TEST_SINCOBERTURA."estado")
FROM ALM_REPORT.AU_TEST_SINCOBERTURA WHERE ALM_REPORT.AU_TEST_SINCOBERTURA."esquema" = "proyecto" ) as estado

from 
ALM_REPORT.PROYECTOS 

';


END CARGAR_GLOBAL_AUDITORIA;

/
