--------------------------------------------------------
--  DDL for Procedure CARGAR_AUD_R1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."CARGAR_AUD_R1" AS 
BEGIN
 execute immediate 'TRUNCATE TABLE ALM_REPORT.AUD_RELEASE';
 
execute immediate  'insert into ALM_REPORT.AUD_RELEASE
SELECT DISTINCT R.REL_ID AS ID_REL, 
R.REL_NAME AS NOMBRE_RELEASE, 
CASE WHEN RQ_USER_04 = ''Pruebas QA'' AND (CUMPLIMIENTO1) = ''CUMPLE'' AND (CUMPLIMIENTO2) = ''CUMPLE'' AND (CUMPLIMIENTO3) = ''CUMPLE'' THEN ''CORRECTOS'' 
WHEN RQ_USER_04 <>  ''Pruebas QA'' THEN ''CORRECTOS''
ELSE ''CON PROBLEMAS'' END AS CUMPLIMIENTO,
''Revisar los ciclos creados en el releases, de no exitir de acuerdo a definición se deben crear'' AS "ACCIÓN A TOMAR",
''SERVIDOR TSOFT'',
''BCH_QA'',
''R1'',
''-'',
REL_USER_TEMPLATE_01,
0,
''/'' ||  RF5.RF_NAME || ''/'' ||  RF4.RF_NAME || ''/'' ||  RF3.RF_NAME || ''/'' ||  RF2.RF_NAME || ''/'' ||  RF1.RF_NAME || ''/'' || RF.RF_NAME AS RUTA

FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES R
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES ON RCYC_PARENT_ID = R.REL_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID 
INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=R.REL_ID
INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID

LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF1 ON RF1.RF_ID = RF.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF1.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF4 ON RF4.RF_ID = RF3.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF5 ON RF5.RF_ID = RF4.RF_PARENT_ID

     
     LEFT JOIN (
      SELECT DISTINCT REL_ID, ''CUMPLE'' AS CUMPLIMIENTO1
      FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES
      LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
      INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
      INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID
      WHERE 1=1
      AND RCYC_USER_01 IN (''Pruebas Estáticas'') 
      AND RQ_USER_04 in (''Pruebas QA'')
      --AND REL_ID = ''1004''
       --AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
    ) CUMPLE1 ON CUMPLE1.REL_ID = R.REL_ID
    
     LEFT JOIN (
      SELECT DISTINCT REL_ID, ''CUMPLE'' AS CUMPLIMIENTO2
      FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES
      LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
      INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
      INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID
      WHERE 1=1
      AND RCYC_USER_01 IN (''Pruebas de IDC'')
      AND RQ_USER_04 in (''Pruebas QA'')
      --AND REL_ID = ''1004''
      -- AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
     ) CUMPLE2 ON CUMPLE2.REL_ID = R.REL_ID       
      
    LEFT JOIN (
      SELECT DISTINCT REL_ID, ''CUMPLE'' AS CUMPLIMIENTO3
      FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES
      LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
      INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
      INNER JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID
      WHERE 1=1
      AND RCYC_USER_01 IN (''Pruebas de Sistema'')
      AND RQ_USER_04 in (''Pruebas QA'')
      --AND REL_ID = ''1004''
      --AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
      ) CUMPLE3 ON CUMPLE3.REL_ID = R.REL_ID
            
WHERE 1=1
--AND(RF.RF_PATH not like ''AAAAAB%''  AND RF.RF_PATH not like ''AAAAAF%'' AND RF.RF_PATH not like ''AAAAAC%'' AND RF.RF_PATH not like ''AAAAAD%'' AND RF.RF_PATH not like ''AAAAAE%'' AND RQ.RQ_REQ_PATH not like ''AAAAAA%'')
AND(RF.RF_PATH not like ''AAAAAD%''  AND RF.RF_PATH not like ''AAAAADAAC%'' AND RF.RF_PATH not like ''AAAAADAAB%'' AND RF.RF_PATH not like ''AAAAAG%'')
AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS



';


execute immediate  'insert into ALM_REPORT.AUD_RELEASE
SELECT DISTINCT R.REL_ID AS ID_REL, 
R.REL_NAME AS NOMBRE_RELEASE, 
CASE WHEN RQ_USER_04 = ''Pruebas QA'' AND (CUMPLIMIENTO1) = ''CUMPLE'' AND (CUMPLIMIENTO2) = ''CUMPLE'' AND (CUMPLIMIENTO3) = ''CUMPLE'' THEN ''CORRECTOS'' 
WHEN RQ_USER_04 <>  ''Pruebas QA'' THEN ''CORRECTOS''
ELSE ''CON PROBLEMAS'' END AS CUMPLIMIENTO,
''Revisar los ciclos creados en el releases, de no exitir de acuerdo a definición se deben crear'' AS "ACCIÓN A TOMAR",
''SERVIDOR TSOFT'',
''QA'',
''R1'',
''-'',
REL_USER_05,
0,
''/'' ||  RF5.RF_NAME || ''/'' ||  RF4.RF_NAME || ''/'' ||  RF3.RF_NAME || ''/'' ||  RF2.RF_NAME || ''/'' ||  RF1.RF_NAME || ''/'' || RF.RF_NAME AS RUTA

FROM QA_QA_DB0.RELEASES R
LEFT JOIN QA_QA_DB0.RELEASE_CYCLES ON RCYC_PARENT_ID = R.REL_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID 
INNER JOIN QA_QA_DB0.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=R.REL_ID
INNER JOIN QA_QA_DB0.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID

LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF1 ON RF1.RF_ID = RF.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF1.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF4 ON RF4.RF_ID = RF3.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF5 ON RF5.RF_ID = RF4.RF_PARENT_ID

     LEFT JOIN (
      SELECT DISTINCT REL_ID, ''CUMPLE'' AS CUMPLIMIENTO1
      FROM QA_QA_DB0.RELEASES
      LEFT JOIN QA_QA_DB0.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
      INNER JOIN QA_QA_DB0.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
      INNER JOIN QA_QA_DB0.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID
      WHERE 1=1
      AND RCYC_USER_01 IN (''Pruebas Estáticas'') 
      AND RQ_USER_04 in (''Pruebas QA'')
      --AND REL_ID = ''1004''
       --AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
    ) CUMPLE1 ON CUMPLE1.REL_ID = R.REL_ID
     
     LEFT JOIN (
      SELECT DISTINCT REL_ID, ''CUMPLE'' AS CUMPLIMIENTO2
      FROM QA_QA_DB0.RELEASES
      LEFT JOIN QA_QA_DB0.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
      INNER JOIN QA_QA_DB0.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
      INNER JOIN QA_QA_DB0.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID
      WHERE 1=1
      AND RCYC_USER_01 IN (''Pruebas de IDC'')
      AND RQ_USER_04 in (''Pruebas QA'')
      --AND REL_ID = ''1004''
      -- AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
     ) CUMPLE2 ON CUMPLE2.REL_ID = R.REL_ID       
      
    LEFT JOIN (
      SELECT DISTINCT REL_ID, ''CUMPLE'' AS CUMPLIMIENTO3
      FROM QA_QA_DB0.RELEASES
      LEFT JOIN QA_QA_DB0.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
      INNER JOIN QA_QA_DB0.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
      INNER JOIN QA_QA_DB0.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID
      WHERE 1=1
      AND RCYC_USER_01 IN (''Pruebas de Sistema'')
      AND RQ_USER_04 in (''Pruebas QA'')
      --AND REL_ID = ''1004''
      --AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
      ) CUMPLE3 ON CUMPLE3.REL_ID = R.REL_ID
            
WHERE 1=1
--AND(RF.RF_PATH not like ''AAAAAB%''  AND RF.RF_PATH not like ''AAAAAF%'' AND RF.RF_PATH not like ''AAAAAC%'' AND RF.RF_PATH not like ''AAAAAD%'' AND RF.RF_PATH not like ''AAAAAE%'' AND RQ.RQ_REQ_PATH not like ''AAAAAA%'')
--AND RQ_USER_04 in (''Pruebas QA'')
--AND RQ_USER_04 in (''Creado'', ''Estática QA'', ''Pendiente Dinámica'', ''Pruebas QA'', ''Suspendido'', ''Ingresado'', ''Fase Estática'', ''Ambientación'', ''Fase Dinámica'', ''Pruebas UAT'', ''Cerrado QA'')
--AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
--AND R.REL_ID = ''1004''
--1954
--1812



';
















execute immediate  'insert into ALM_REPORT.AUD_RELEASE
SELECT
DISTINCT REL_ID AS ID_REL,
REL_NAME AS NOMBRE_RELEASES,
CASE WHEN RQ.RQ_REQ_ID IS NULL THEN ''CON PROBLEMAS'' ELSE ''CORRECTOS'' END  AS CUMPLIMIENTO,
''Se debe realizar la trazabilidad con el requerimiento'' AS "ACCIÓN A TOMAR",
''SERVIDOR TSOFT'',
''BCH_QA'',
''R2'',
''-'',
REL_USER_TEMPLATE_01,
0,
''/'' ||  RF5.RF_NAME || ''/'' ||  RF4.RF_NAME || ''/'' ||  RF3.RF_NAME || ''/'' ||  RF2.RF_NAME || ''/'' ||  RF1.RF_NAME || ''/'' || RF.RF_NAME AS RUTA


FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES R
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON  RF.RF_ID = REL_PARENT_ID 
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID

LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF1 ON RF1.RF_ID = RF.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF1.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF4 ON RF4.RF_ID = RF3.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF5 ON RF5.RF_ID = RF4.RF_PARENT_ID

WHERE 1=1
--AND(RF.RF_PATH not like ''AAAAAB%''  AND RF.RF_PATH not like ''AAAAAF%'' AND RF.RF_PATH not like ''AAAAAC%'' AND RF.RF_PATH not like ''AAAAAD%'' AND RF.RF_PATH not like ''AAAAAE%'' AND RQ.RQ_REQ_PATH not like ''AAAAAA%'')
AND(RF.RF_PATH not like ''AAAAAD%''  AND RF.RF_PATH not like ''AAAAADAAC%'' AND RF.RF_PATH not like ''AAAAADAAB%'' AND RF.RF_PATH not like ''AAAAAG%'')
AND RQ_TYPE_ID IN (119,117,107)--116 MANTENCIONES PRODUCTIVAS
--AND RQ.RQ_REQ_ID IS NULL


';

execute immediate  'insert into ALM_REPORT.AUD_RELEASE
SELECT
DISTINCT REL_ID AS ID_REL,
REL_NAME AS NOMBRE_RELEASES,
CASE WHEN RQ.RQ_REQ_ID IS NULL THEN ''CON PROBLEMAS'' ELSE ''CORRECTOS'' END  AS CUMPLIMIENTO,
''Se debe realizar la trazabilidad con el requerimiento'' AS "ACCIÓN A TOMAR",
''SERVIDOR TSOFT'',
''QA'',
''R2'',
''-'',
REL_USER_05,
0,
''/'' ||  RF5.RF_NAME || ''/'' ||  RF4.RF_NAME || ''/'' ||  RF3.RF_NAME || ''/'' ||  RF2.RF_NAME || ''/'' ||  RF1.RF_NAME || ''/'' || RF.RF_NAME AS RUTA

FROM QA_QA_DB0.RELEASES R
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = REL_PARENT_ID 
LEFT JOIN QA_QA_DB0.REQ_RELEASES RQR ON RQR.RQRL_RELEASE_ID=REL_ID
LEFT JOIN QA_QA_DB0.REQ RQ ON RQ.RQ_REQ_ID=RQR.RQRL_REQ_ID

LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF1 ON RF1.RF_ID = RF.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF1.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF4 ON RF4.RF_ID = RF3.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF5 ON RF5.RF_ID = RF4.RF_PARENT_ID


WHERE 1=1



';











execute immediate  'insert into ALM_REPORT.AUD_RELEASE
SELECT REL_ID ID_REL, 
REL_NAME NOMBRE_REL,
CASE WHEN COUNT(DISTINCT(CF_ITEM_ID)) = 0 THEN ''CON PROBLEMAS'' ELSE ''CORRECTOS'' END AS CUMPLIMIENTO,
''-'',
''SERVIDOR TSOFT'',
''BCH_QA'',
''R3'',
RCYC_NAME NOMBRE_CICLO, 
REL_USER_TEMPLATE_01 JPQA, 
COUNT(DISTINCT(CF_ITEM_ID)) TOTAL_TEST_SET,
''/'' ||  RF5.RF_NAME || ''/'' ||  RF4.RF_NAME || ''/'' ||  RF3.RF_NAME || ''/'' ||  RF2.RF_NAME || ''/'' ||  RF1.RF_NAME || ''/'' || RF.RF_NAME AS RUTA


FROM BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASES R
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON  RF.RF_ID = REL_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.CYCL_FOLD ON CF_ASSIGN_RCYC = RCYC_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.CYCLE ON CY_FOLDER_ID = CF_ITEM_ID

LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF1 ON RF1.RF_ID = RF.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF1.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF4 ON RF4.RF_ID = RF3.RF_PARENT_ID
LEFT JOIN BCH_QA_CERTIFICACIÓN_BCH_QA_D.RELEASE_FOLDERS RF5 ON RF5.RF_ID = RF4.RF_PARENT_ID


WHERE 1=1
AND RCYC_NAME NOT IN (''Pruebas Estaticas'', ''Pruebas Estáticas'', ''Fase Estatica'', ''Pruebas Estática'', ''Pruebas Estatica'')
--AND(RF.RF_PATH not like ''AAAAAB%''  AND RF.RF_PATH not like ''AAAAAF%'' AND RF.RF_PATH not like ''AAAAAC%'' AND RF.RF_PATH not like ''AAAAAD%'' AND RF.RF_PATH not like ''AAAAAE%'')
AND(RF.RF_PATH not like ''AAAAAD%''  AND RF.RF_PATH not like ''AAAAADAAC%'' AND RF.RF_PATH not like ''AAAAADAAB%'' AND RF.RF_PATH not like ''AAAAAG%'')


GROUP BY REL_ID, 
REL_NAME,
RCYC_NAME, 
REL_USER_TEMPLATE_01,
RF5.RF_NAME,
RF4.RF_NAME,
RF3.RF_NAME,
RF2.RF_NAME,
RF1.RF_NAME,
RF.RF_NAME
--HAVING COUNT(DISTINCT(CF_ITEM_ID)) <= 0


'; 


execute immediate  'insert into ALM_REPORT.AUD_RELEASE
SELECT REL_ID ID_REL, 
REL_NAME NOMBRE_REL,
CASE WHEN COUNT(DISTINCT(CF_ITEM_ID)) = 0 THEN ''CON PROBLEMAS'' ELSE ''CORRECTOS'' END AS CUMPLIMIENTO,
''-'',
''SERVIDOR TSOFT'',
''QA'',
''R3'',
RCYC_NAME NOMBRE_CICLO, 
REL_USER_05 JPQA, 
COUNT(DISTINCT(CF_ITEM_ID)) TOTAL_TEST_SET,
''/'' ||  RF5.RF_NAME || ''/'' ||  RF4.RF_NAME || ''/'' ||  RF3.RF_NAME || ''/'' ||  RF2.RF_NAME || ''/'' ||  RF1.RF_NAME || ''/'' || RF.RF_NAME AS RUTA


FROM QA_QA_DB0.RELEASES R
LEFT JOIN QA_QA_DB0.RELEASE_CYCLES ON RCYC_PARENT_ID = REL_ID
JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = REL_PARENT_ID
LEFT JOIN QA_QA_DB0.CYCL_FOLD ON CF_ASSIGN_RCYC = RCYC_ID
LEFT JOIN QA_QA_DB0.CYCLE ON CY_FOLDER_ID = CF_ITEM_ID

LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = R.REL_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF1 ON RF1.RF_ID = RF.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF2 ON RF2.RF_ID = RF1.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF3 ON RF3.RF_ID = RF2.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF4 ON RF4.RF_ID = RF3.RF_PARENT_ID
LEFT JOIN QA_QA_DB0.RELEASE_FOLDERS RF5 ON RF5.RF_ID = RF4.RF_PARENT_ID

WHERE 1=1
GROUP BY REL_ID, 
REL_NAME,
RCYC_NAME, 
REL_USER_05,
RF5.RF_NAME,
RF4.RF_NAME,
RF3.RF_NAME,
RF2.RF_NAME,
RF1.RF_NAME,
RF.RF_NAME

';







execute immediate  'insert into ALM_REPORT.AUD_RELEASE 
select * from AUD_RELEASE@SERVER_BCH
';






END;

/
