--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-22-2017   
--------------------------------------------------------
@/Users/pcarrasco/Desktop/SQL/carga_detalle_release.sql
@/Users/pcarrasco/Desktop/SQL/CARGA_MANTENCIONES.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_AHORRO.sql
@/Users/pcarrasco/Desktop/SQL/Cargar_AU_REL_PY.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_AUD_R1.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_CASOS_POR_ESCENARIO.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_360.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_360_BUG.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_360_PRUEBA.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_360_RUNS.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_AUTOMATICO.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_DEF_INNOVACION.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_EJE_INNOVACION.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DATA_EXTRACT_MENSUAL_TB.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DEFEC.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DSH_ESTATICO.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_DSH_ESTATICO_RESPALDO.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_GLOBAL_AUDITORIA.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_HIS_INC.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_IMPACTO_CRS.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_INC_DEF.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_INC_EJEC.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_INCIDENTES.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_MIDDLEWARE.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_PANEL_CASOS.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_RELEASES.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_TABLA_COBER_REQ.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_TABLATEMPCPEXITO.sql
@/Users/pcarrasco/Desktop/SQL/CARGAR_TABLATEMPCPEXITO_A.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_BUG_SINFECHACIERRE.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_BUG_TRAZABILIDAD.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REL_CARPETA_TESTSET.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REL_CICLOS_BCHQA.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REL_NOMBRECICLOS.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REL_TRAZABILIDADREQ.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REQ_NOMBRERELEASE.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REQ_NOMENCLATURAHIJOS.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REQ_SINCOBERTURA.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_REQ_SINTRAZABILIDAD.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_TEST_CAMPOSVACIOS.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_TEST_DESCRIPCION.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_TEST_PASOS.sql
@/Users/pcarrasco/Desktop/SQL/cargarAU_TEST_SINCOBERTURA.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_REQ_SIN_COB.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_REQ_SIN_TRAZ.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_SIN_REQ.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_TEST_CAMPOINV.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_TEST_CAMPOVAC.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_TEST_MENOS2PASOS.sql
@/Users/pcarrasco/Desktop/SQL/CARGARAUDIT_TEST_SIN_COB.sql
@/Users/pcarrasco/Desktop/SQL/cargarAuditoriaPActivos.sql
@/Users/pcarrasco/Desktop/SQL/cargarAuPActivos_fechaManual.sql
@/Users/pcarrasco/Desktop/SQL/cargarAutomatCreaYMod.sql
@/Users/pcarrasco/Desktop/SQL/cargarAutomatEjecucion.sql
@/Users/pcarrasco/Desktop/SQL/cargarAutomatEjecucion2.sql
@/Users/pcarrasco/Desktop/SQL/cargarAutomatizadosExcel.sql
@/Users/pcarrasco/Desktop/SQL/cargarCALIDAD_DESARROLLO_AGIL.sql
@/Users/pcarrasco/Desktop/SQL/cargarConteoJPQA.sql
@/Users/pcarrasco/Desktop/SQL/cargarConteoTest.sql
@/Users/pcarrasco/Desktop/SQL/cargarCurva1.sql
@/Users/pcarrasco/Desktop/SQL/cargarCurva2.sql
@/Users/pcarrasco/Desktop/SQL/CARGARDATOS_CLAUDIO.sql
@/Users/pcarrasco/Desktop/SQL/cargarDatosALM.sql
@/Users/pcarrasco/Desktop/SQL/cargarDatosALM_fechaManual.sql
@/Users/pcarrasco/Desktop/SQL/cargarDatosALM_MES.sql
@/Users/pcarrasco/Desktop/SQL/cargarDatosALM_Vol.sql
@/Users/pcarrasco/Desktop/SQL/cargarDefectos.sql
@/Users/pcarrasco/Desktop/SQL/cargarDefectos_fechaManual.sql
@/Users/pcarrasco/Desktop/SQL/cargarDefectos_MES.sql
@/Users/pcarrasco/Desktop/SQL/cargarDetalleNuevaInternet.sql
@/Users/pcarrasco/Desktop/SQL/cargarEstadosRequerimientos.sql
@/Users/pcarrasco/Desktop/SQL/cargarListadoProyectos.sql
@/Users/pcarrasco/Desktop/SQL/cargarListadoReqyEstados.sql
@/Users/pcarrasco/Desktop/SQL/cargarListadoReqyEstados_bchqa.sql
@/Users/pcarrasco/Desktop/SQL/cargarListadoReqyEstados_qa_qa.sql
@/Users/pcarrasco/Desktop/SQL/cargarListadoTrazabilidad.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyeccion.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyectos.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyectos_sin_IDC.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyectosAgiles.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyectosGrandes.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyectosGrandes_jpino.sql
@/Users/pcarrasco/Desktop/SQL/cargarProyectosPorMes.sql
@/Users/pcarrasco/Desktop/SQL/CARGARPRUEBA360.sql
@/Users/pcarrasco/Desktop/SQL/cargarQueryHP1.sql
@/Users/pcarrasco/Desktop/SQL/cargarQueryHP2.sql
@/Users/pcarrasco/Desktop/SQL/cargarQueryHP3.sql
@/Users/pcarrasco/Desktop/SQL/CARGARQUERYHP4.sql
@/Users/pcarrasco/Desktop/SQL/cargarReleaseSinREQ.sql
@/Users/pcarrasco/Desktop/SQL/esquemasSinReleases.sql
@/Users/pcarrasco/Desktop/SQL/P_TESTDEV.sql
@/Users/pcarrasco/Desktop/SQL/querysCristian.sql
@/Users/pcarrasco/Desktop/SQL/SP_CLOUD_CDN.sql
@/Users/pcarrasco/Desktop/SQL/VOLUMETRIA_PROYECTOS.sql
