--------------------------------------------------------
--  DDL for Procedure SP_CLOUD_CDN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ALM_REPORT"."SP_CLOUD_CDN" AS 
BEGIN
 execute immediate 'TRUNCATE TABLE ALM_REPORT.CLOUD_CDN';
 
execute immediate  'insert into ALM_REPORT.CLOUD_CDN

SELECT 
REL_ID AS Id_Release, 
REL_NAME AS Nombre_Release, 
REL_USER_05 AS JPQA, 
REL_USER_02 AS Jefe_Desarrollo,
RF.RF_NAME AS Nombre_Carpeta,
RCYC_ID AS Id_Ciclo, 
RCYC_NAME AS Nombre_Ciclo, 
RCYC_USER_03 AS Tipo_Prueba,
CY_CYCLE_ID AS Id_Historia, 
CY_CYCLE AS Nombre_Historia, 
CY_USER_TEMPLATE_01 AS Funcionalidad,
TS_TYPE AS TIPO_CASO, 
TC_TEST_ID AS Id_Test_Tc, 
TC_TESTCYCL_ID AS Id_Instancia, 
TC_STATUS AS Estado_Instancia, 
TC_TESTER_NAME AS Tester, 
TC_EXEC_DATE AS Fecha_Exec_Instancia,
SUB_DEF.ID_Defecto,
SUB_DEF.Severidad_Defecto,
SUB_DEF.Estado_Defecto,
TS.TS_NAME "Nombre CP",
SUB_DEF.Summary,
SUB_DEF.Proveedor "Proveedor",
TC2.TC_TEST_CONFIG_ID "id Config"

FROM QA_QA_DB0.RELEASES REL
JOIN QA_QA_DB0.RELEASE_FOLDERS RF ON  RF.RF_ID = REL.REL_PARENT_ID 
JOIN QA_QA_DB0.RELEASE_CYCLES RCYC ON RCYC.RCYC_PARENT_ID = REL.REL_ID
LEFT JOIN QA_QA_DB0.CYCL_FOLD CF ON CF.CF_ASSIGN_RCYC = RCYC.RCYC_ID
LEFT JOIN QA_QA_DB0.CYCLE CY ON CY.CY_FOLDER_ID = CF.CF_ITEM_ID
LEFT JOIN QA_QA_DB0.TESTCYCL TC2 ON TC2.TC_CYCLE_ID = CY.CY_CYCLE_ID
LEFT JOIN QA_QA_DB0.TEST TS ON TS.TS_TEST_ID = TC2.TC_TEST_ID

LEFT JOIN (
SELECT DISTINCT
BUG.BG_BUG_ID           AS ID_Defecto,
BUG.BG_SEVERITY         AS Severidad_Defecto,
BUG.BG_SUBJECT          AS Subject,
BUG.BG_DETECTION_DATE   AS Fecha_Detección,
BUG.BG_DETECTED_BY      AS Detectado_Por,
BUG.BG_SUMMARY          AS Summary,
BUG.BG_STATUS           AS Estado_Defecto,
RCYC.RCYC_NAME          AS Ciclo,
RCYC.RCYC_ID            AS ID_CICLO,
TS_TEST_ID              AS Test_ID,
TS_NAME                 AS Nombre_CP,
ln_link_id              AS Id_Link,
BUG.BG_USER_07          AS Proveedor,
TC.TC_TEST_CONFIG_ID    AS Id_Config

FROM QA_QA_DB0.BUG BUG
LEFT JOIN QA_QA_DB0.ALL_LISTS AL ON AL.AL_ITEM_ID = BUG.BG_SUBJECT
LEFT JOIN QA_QA_DB0.LINK ON LN_BUG_ID = BG_BUG_ID  AND LN_ENTITY_TYPE = ''TESTCYCL''
LEFT JOIN QA_QA_DB0.TESTCYCL TC ON TC.TC_TESTCYCL_ID = LN_ENTITY_ID
LEFT JOIN QA_QA_DB0.TEST ON TC.TC_TEST_ID = TS_TEST_ID
LEFT JOIN QA_QA_DB0.RELEASES R ON R.REL_ID = BG_TARGET_REL OR BG_DETECTED_IN_REL = R.REL_ID
LEFT JOIN QA_QA_DB0.RELEASE_CYCLES RCYC ON RCYC.RCYC_ID = BG_DETECTED_IN_RCYC OR BG_TARGET_RCYC = RCYC.RCYC_ID

UNION ALL

SELECT DISTINCT
BUG.BG_BUG_ID           AS ID_Defecto,
BUG.BG_SEVERITY         AS Severidad_Defecto,
BUG.BG_SUBJECT          AS Subject,
BUG.BG_DETECTION_DATE   AS Fecha_Detección,
BUG.BG_DETECTED_BY      AS Detectado_Por,
BUG.BG_SUMMARY          AS Summary,
BUG.BG_STATUS           AS Estado_Defecto,
RCYC.RCYC_NAME          AS Ciclo,
RCYC.RCYC_ID            AS ID_CICLO,
TS_TEST_ID              AS Test_ID,
TS_NAME                 AS Nombre_CP,
ln_link_id              AS Id_Link,
BUG.BG_USER_07          AS Proveedor,
TC_TEST_CONFIG_ID       AS Id_Config

FROM QA_QA_DB0.BUG BUG
LEFT JOIN QA_QA_DB0.LINK ON LN_BUG_ID = BG_BUG_ID AND LN_ENTITY_TYPE = ''STEP''
LEFT JOIN QA_QA_DB0.STEP ON st_id = LN_ENTITY_ID
LEFT JOIN QA_QA_DB0.RUN ON RN_RUN_ID = ST_RUN_ID
LEFT JOIN QA_QA_DB0.TESTCYCL ON TC_TESTCYCL_ID = RN_TESTCYCL_ID
LEFT JOIN QA_QA_DB0.TEST ON TS_TEST_ID = TC_TEST_ID
LEFT JOIN QA_QA_DB0.CYCLE CY  ON CY.CY_CYCLE_ID = TC_CYCLE_ID
LEFT JOIN QA_QA_DB0.RELEASES R ON R.REL_ID = BG_TARGET_REL OR BG_DETECTED_IN_REL = R.REL_ID
LEFT JOIN QA_QA_DB0.RELEASE_CYCLES RCYC ON RCYC.RCYC_ID = BG_DETECTED_IN_RCYC OR BG_TARGET_RCYC = RCYC.RCYC_ID

Union all

SELECT DISTINCT
BUG.BG_BUG_ID           AS ID_Defecto,
BUG.BG_SEVERITY         AS Severidad_Defecto,
BUG.BG_SUBJECT          AS Subject,
BUG.BG_DETECTION_DATE   AS Fecha_Detección,
BUG.BG_DETECTED_BY      AS Detectado_Por,
BUG.BG_SUMMARY          AS Summary,
BUG.BG_STATUS           AS Estado_Defecto,
RCYC.RCYC_NAME          AS Ciclo,
RCYC.RCYC_ID            AS ID_CICLO,
TS_TEST_ID              AS Test_ID,
TS_NAME                 AS Nombre_CP,
ln_link_id              AS Id_Link,
BUG.BG_USER_07          AS Proveedor,
TC_TEST_CONFIG_ID       AS Id_Config

--RUN
FROM QA_QA_DB0.BUG BUG
LEFT JOIN QA_QA_DB0.LINK ON LN_BUG_ID = BG_BUG_ID AND LN_ENTITY_TYPE = ''RUN''
LEFT JOIN QA_QA_DB0.ALL_LISTS AL ON AL.AL_ITEM_ID = BUG.BG_SUBJECT
LEFT JOIN QA_QA_DB0.RUN ON LN_ENTITY_ID = RN_RUN_ID
LEFT JOIN QA_QA_DB0.TESTCYCL ON TC_TESTCYCL_ID = RN_TESTCYCL_ID
LEFT JOIN QA_QA_DB0.TEST ON TC_TEST_ID = TS_TEST_ID
LEFT JOIN QA_QA_DB0.RELEASES R ON R.REL_ID = BG_TARGET_REL OR BG_DETECTED_IN_REL = R.REL_ID
LEFT JOIN QA_QA_DB0.RELEASE_CYCLES RCYC ON RCYC.RCYC_ID = BG_DETECTED_IN_RCYC OR BG_TARGET_RCYC = RCYC.RCYC_ID

)SUB_DEF ON SUB_DEF.Id_Config = TC2.TC_TEST_CONFIG_ID 

WHERE 1=1
AND(RF_PATH like ''AAAAADAAA%'')/*Considera todo lo que esta dentro de la carpeta Centro de Negocios*/


'; 
END;

/
